### ISSUE TITLE
Toggling Codecov prevents tested lines from appearing again

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph-codecov#13] opened 2018-11-30 18:57 UTC
![toggle codecov sourcegraph](https://user-images.githubusercontent.com/133014/49308921-86dd8d00-f48e-11e8-9597-38bdff5bda21.gif)

Steps to reproduce:
1. View https://sourcegraph.com/github.com/theupdateframework/notary@fb795b0bc868746ed2efa2cd7109346bc7ddf0a4/-/blob/server/storage/tuf_store.go
1. Observe Codecov tested code lines are visisble.
1. Click the Coverage button.
1. Observe Codecov tested lines are not visible.
1. Click the Coverage button again. 
1. Observe a flash of tested code lines. 

Further clicking of the Coverage button fails to show the tested lines again.

**Comment by sqs** [comment] 2018-11-30 19:08
Is there another extension running that is also publishing line decorations? What other extensions are active? (In the bottom right Ext menu.)

Any JS errors?

**Comment by ryan-blunden** [comment] 2018-11-30 19:11
Not seeing any errors.

Extensions enabled:
- chris/lang-go
- sourcegraph/codecov
- sourcegraph/code-discussions
- chris/graphql
- sqs/sourcegraph-python
- sourcegraph/line-counter

Will try disabling all other extensions

**Comment by sqs** [comment] 2018-11-30 19:14
I suspect this is caused by
https://github.com/sourcegraph/sourcegraph/issues/74 but not sure.

**Comment by ryan-blunden** [comment] 2018-11-30 19:14
Disabled all extensions except Codecov. Works.

Enabled Code discussions and the issue re-appears

**Comment by sqs** [comment] 2018-12-03 07:38
OK, this is 
https://github.com/sourcegraph/sourcegraph/issues/74. Closing as dup.

**Closed by sqs** 2018-12-03 07:38 UTC
